# Generated by Django 4.1.7 on 2023-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('AGENCY', 'agency'), ('REALTOR', 'realtor'), ('BUILDER', 'builder'), ('MANAGER', 'manager'), ('SALE_MANGER', 'sale manager'), ('BANK', 'bank'), ('MODERATOR', 'moderator')], max_length=30),
        ),
    ]
