# Generated by Django 4.1.7 on 2023-04-23 09:58

import builders.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_auth', '0001_initial'),
        ('builders', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('brand_name', models.CharField(blank=True, max_length=30)),
                ('legal_name', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('inn', models.CharField(blank=True, max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to=builders.utils.upload_builder_logo)),
                ('license', models.FileField(blank=True, null=True, upload_to=builders.utils.upload_builder_license)),
                ('license_period', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='builders.block')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=builders.utils.upload_manager_photo)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='builders.builder')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('deadline', models.CharField(blank=True, max_length=10)),
                ('ceiling_height', models.CharField(blank=True, max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('floor', models.CharField(blank=True, max_length=15)),
                ('total_apartment', models.SmallIntegerField(default=1)),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to=builders.utils.upload_resident_banner)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.builder')),
                ('building_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buildingclass')),
                ('building_type', models.ManyToManyField(blank=True, to='main.buildingtype')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.city')),
                ('decoration', models.ManyToManyField(blank=True, to='main.decoration')),
                ('elevator', models.ManyToManyField(blank=True, to='main.elevator')),
                ('facade', models.ManyToManyField(blank=True, to='main.facade')),
                ('heating', models.ManyToManyField(blank=True, to='main.heating')),
                ('kitchen', models.ManyToManyField(blank=True, to='main.kitchen')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.manager')),
                ('parking', models.ManyToManyField(blank=True, to='main.parking')),
            ],
            options={
                'db_table': 'resident_complex',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='builders.entrance')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.residentcomplex')),
            ],
            options={
                'db_table': 'complex_picture',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buildingtype'),
        ),
        migrations.AddField(
            model_name='block',
            name='resident_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.residentcomplex'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='decoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartmentdecoration'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='builders.floor'),
        ),
    ]
