# Generated by Django 4.1.7 on 2023-04-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('builders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.floortype'),
        ),
    ]
