# Generated by Django 4.1.7 on 2023-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0003_floor_floor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentcomplex',
            name='ceiling_height',
        ),
        migrations.AddField(
            model_name='apartment',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='residentcomplex',
            name='ceiling_height_from',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='residentcomplex',
            name='ceiling_height_to',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
