# Generated by Django 4.1.7 on 2023-04-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apartmenttype'),
        ('builders', '0004_remove_residentcomplex_ceiling_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.apartmenttype'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='decoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartmentdecoration', verbose_name='отделка'),
        ),
    ]
