# Generated by Django 4.1.7 on 2023-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0005_apartment_type_alter_apartment_decoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
