# Generated by Django 4.1.7 on 2023-04-23 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0006_block_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 16, 56, 37, 494558, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
