# Generated by Django 4.1.7 on 2023-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0007_block_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
