# Generated by Django 4.1.7 on 2023-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0009_alter_apartment_decoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
