# Generated by Django 4.1.7 on 2023-04-27 06:22

import builders.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0011_remove_floor_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=builders.utils.upload_block_floor),
        ),
    ]
