# Generated by Django 4.1.7 on 2023-04-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_apartmentstatus_options_and_more'),
        ('builders', '0014_remove_apartment_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.apartmentstatus'),
            preserve_default=False,
        ),
    ]
