# Generated by Django 4.1.7 on 2023-04-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0015_apartment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image_2',
        ),
    ]
