# Generated by Django 4.1.7 on 2023-04-28 05:24

import builders.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0017_apartment_image_1_apartment_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=builders.utils.upload_manager_photo),
        ),
    ]
