# Generated by Django 4.1.7 on 2023-05-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0002_alter_role_name'),
        ('builders', '0022_alter_floor_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builders.manager')),
            ],
        ),
    ]
