# Generated by Django 4.1.7 on 2023-05-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0023_salemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemanager',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='builders.manager'),
        ),
    ]
