# Generated by Django 4.1.7 on 2023-05-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0024_alter_salemanager_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('sure_name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builders.salemanager')),
            ],
        ),
    ]
