# Generated by Django 4.1.7 on 2023-05-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_salemanageaction_salemanageraction'),
        ('builders', '0025_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.salemanageraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='info_apartment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
