# Generated by Django 4.1.7 on 2023-05-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0027_client_social_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='social_medias',
        ),
    ]
