# Generated by Django 4.1.7 on 2023-05-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0028_remove_client_social_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='social_medias',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
