# Generated by Django 4.1.7 on 2023-05-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0030_alter_floor_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='total_square',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
