# Generated by Django 4.1.7 on 2023-05-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0031_apartment_total_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='builders.apartment'),
            preserve_default=False,
        ),
    ]
