# Generated by Django 4.1.7 on 2023-05-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0034_apartmentprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apartmentprice',
            table='apartment_price',
        ),
    ]
