# Generated by Django 4.1.7 on 2023-05-08 03:59

import builders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0035_alter_apartmentprice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentprice',
            name='created_at',
            field=models.DateField(default=builders.utils.get_cur_date),
        ),
    ]
