# Generated by Django 4.1.7 on 2023-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_socialmedia'),
        ('builders', '0037_client_recall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='social_medias',
        ),
        migrations.AddField(
            model_name='client',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='clients', to='main.socialmedia'),
        ),
    ]
