# Generated by Django 4.1.7 on 2023-05-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_socialmedia'),
        ('builders', '0037_client_recall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='social_medias',
        ),
        migrations.AddField(
            model_name='client',
            name='social_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.socialmedia'),
            preserve_default=False,
        ),
    ]
