# Generated by Django 4.1.7 on 2023-05-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0038_remove_client_social_medias_client_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='social_media',
        ),
    ]
