# Generated by Django 4.1.7 on 2023-04-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDecoration',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'отделка квартиры',
                'db_table': 'apartment_decoration',
            },
        ),
        migrations.CreateModel(
            name='BuildingClass',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Класс',
                'db_table': 'building_class',
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Тип дома',
                'db_table': 'building_type',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Отделка',
                'db_table': 'decoration',
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Лифт',
                'db_table': 'elevator',
            },
        ),
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Фасад',
                'db_table': 'facade',
            },
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'тип этажа',
                'db_table': 'floor_type',
            },
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'отопление',
                'db_table': 'heating',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'кухня',
                'db_table': 'kitchen',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'парковка',
                'db_table': 'parking',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.region')),
            ],
        ),
    ]
