# Generated by Django 4.1.7 on 2023-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'тип квартиры',
                'db_table': 'apartment_type',
            },
        ),
    ]
