# Generated by Django 4.1.7 on 2023-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apartmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
