# Generated by Django 4.1.7 on 2023-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_apartmentstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManageAction',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
