# Generated by Django 4.1.7 on 2023-05-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_salemanageaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleManageAction',
            new_name='SaleManagerAction',
        ),
    ]
